# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Redis installation tasks
  block:
    - name: Validate Redis configuration
      when: redis_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Redis
      when: redis_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-redis
    - install-all
    - install-redis

- name: Perform Redis uninstallation tasks
  block:
    - name: Uninstall Redis
      when: not redis_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-redis
